const commonFields = {
  slug: { key: "slug", label: "Slug (URL)", type: "slug", required: true },
  title: { key: "title", label: "Title", type: "text", required: true },
  short: { key: "short", label: "Short description", type: "textarea" },
  category: { key: "category", label: "Category", type: "text" },
  description: { key: "description", label: "Description", type: "textarea" },
};

export const schemas = {
  portfolioItems: {
    label: "Portfolio",
    singular: "Portfolio Item",
    idKey: "slug",
    titleKey: "title",
    fields: [
      commonFields.slug,
      commonFields.title,
      commonFields.category,
      commonFields.short,
      { key: "description", label: "Description", type: "textarea" },
      { key: "longDescription", label: "Long description", type: "textarea" },
      {
        key: "cover",
        label: "Cover media",
        type: "media",
        subFields: [
          { key: "type", label: "Type", type: "select", options: ["image", "video"] },
          { key: "src", label: "File / URL", type: "media-src" },
          { key: "poster", label: "Poster (for video)", type: "media-src" },
          { key: "alt", label: "Alt text", type: "text" },
        ],
      },
      { key: "resultPoints", label: "Result points (one per line)", type: "string-list" },
      { key: "roles", label: "Roles (one per line)", type: "string-list" },
      { key: "tools", label: "Tools (one per line)", type: "string-list" },
      {
        key: "metrics",
        label: "Metrics",
        type: "objects-list",
        subFields: [
          { key: "label", label: "Label", type: "text" },
          { key: "value", label: "Value", type: "text" },
        ],
      },
      { key: "caseStudySlug", label: "Case study slug", type: "text" },
      { key: "serviceSlug", label: "Service slug", type: "text" },
    ],
  },

  serviceCategories: {
    label: "Services",
    singular: "Service",
    idKey: "slug",
    titleKey: "name",
    fields: [
      commonFields.slug,
      { key: "name", label: "Name", type: "text", required: true },
      { key: "short", label: "Short tagline", type: "text" },
      { key: "tagline", label: "Hero tagline", type: "textarea" },
      { key: "longIntro", label: "Long intro", type: "textarea" },
      { key: "color", label: "Accent (gold/blue)", type: "select", options: ["gold", "blue"] },
      {
        key: "cover",
        label: "Cover media",
        type: "media",
        subFields: [
          { key: "type", label: "Type", type: "select", options: ["image", "video"] },
          { key: "src", label: "File / URL", type: "media-src" },
          { key: "poster", label: "Poster (for video)", type: "media-src" },
          { key: "alt", label: "Alt text", type: "text" },
        ],
      },
      { key: "included", label: "What's included (one per line)", type: "string-list" },
      {
        key: "approach",
        label: "Approach principles",
        type: "objects-list",
        subFields: [
          { key: "title", label: "Title", type: "text" },
          { key: "text", label: "Text", type: "textarea" },
        ],
      },
      { key: "deliverables", label: "Deliverables (one per line)", type: "string-list" },
      { key: "caseStudySlug", label: "Case study slug", type: "text" },
      { key: "recommendedPlan", label: "Recommended plan id", type: "text" },
    ],
  },

  teamRoles: {
    label: "Team",
    singular: "Team Role",
    idKey: "slug",
    titleKey: "name",
    fields: [
      commonFields.slug,
      { key: "name", label: "Name", type: "text", required: true },
      { key: "role", label: "Role", type: "text" },
      { key: "short", label: "Short tagline", type: "text" },
      { key: "photo", label: "Photo", type: "media-src" },
      { key: "photoAlt", label: "Photo alt", type: "text" },
      { key: "intro", label: "Intro", type: "textarea" },
      { key: "tags", label: "Tags (one per line)", type: "string-list" },
      { key: "owns", label: "What they own (one per line)", type: "string-list" },
      { key: "worksOn", label: "Works on (one per line)", type: "string-list" },
      { key: "relatedServiceSlug", label: "Related service slug", type: "text" },
      { key: "footer", label: "Footer note", type: "textarea" },
    ],
  },

  testimonials: {
    label: "Testimonials",
    singular: "Testimonial",
    idKey: "id",
    titleKey: "author",
    fields: [
      { key: "id", label: "ID (unique)", type: "slug", required: true },
      { key: "type", label: "Type", type: "select", options: ["text", "video"] },
      { key: "quote", label: "Quote", type: "textarea" },
      { key: "author", label: "Author", type: "text", required: true },
      { key: "role", label: "Role", type: "text" },
      { key: "location", label: "Location", type: "text" },
      { key: "industry", label: "Industry", type: "text" },
      { key: "result", label: "Result badge", type: "text" },
      { key: "accent", label: "Accent (gold/blue)", type: "select", options: ["gold", "blue"] },
      { key: "caseStudy", label: "Case study slug", type: "text" },
      { key: "videoSrc", label: "Video src (for video)", type: "media-src" },
      { key: "poster", label: "Poster (for video)", type: "media-src" },
    ],
  },

  caseStudies: {
    label: "Case Studies",
    singular: "Case Study",
    idKey: "slug",
    titleKey: "title",
    fields: [
      commonFields.slug,
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      commonFields.title,
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "industry", label: "Industry", type: "text" },
      { key: "location", label: "Location", type: "text" },
      { key: "timeline", label: "Timeline", type: "text" },
      { key: "services", label: "Services used (one per line)", type: "string-list" },
      {
        key: "heroMedia",
        label: "Hero media",
        type: "media",
        subFields: [
          { key: "type", label: "Type", type: "select", options: ["image", "video"] },
          { key: "src", label: "File / URL", type: "media-src" },
          { key: "alt", label: "Alt text", type: "text" },
        ],
      },
      {
        key: "metrics",
        label: "Before/After metrics",
        type: "objects-list",
        subFields: [
          { key: "label", label: "Label", type: "text" },
          { key: "before", label: "Before", type: "text" },
          { key: "after", label: "After", type: "text" },
        ],
      },
      { key: "challenge", label: "Challenge", type: "textarea" },
      { key: "approach", label: "Approach (one per line)", type: "string-list" },
      { key: "execution", label: "Execution (one per line)", type: "string-list" },
      {
        key: "testimonial",
        label: "Testimonial",
        type: "media",
        subFields: [
          { key: "quote", label: "Quote", type: "textarea" },
          { key: "author", label: "Author", type: "text" },
          { key: "role", label: "Role", type: "text" },
        ],
      },
      { key: "nextSteps", label: "Next steps", type: "textarea" },
      { key: "tags", label: "Tags (one per line)", type: "string-list" },
    ],
  },

  pricingPlans: {
    label: "Pricing",
    singular: "Pricing Plan",
    idKey: "id",
    titleKey: "name",
    fields: [
      { key: "id", label: "ID", type: "slug", required: true },
      { key: "name", label: "Name", type: "text", required: true },
      { key: "tagline", label: "Tagline", type: "text" },
      { key: "monthly", label: "Monthly price", type: "text" },
      { key: "monthlyNote", label: "Price note", type: "text" },
      { key: "bestFor", label: "Best for", type: "textarea" },
      { key: "cta", label: "CTA label", type: "text" },
      { key: "highlights", label: "Highlights (one per line)", type: "string-list" },
      { key: "accent", label: "Accent (gold/blue)", type: "select", options: ["gold", "blue"] },
      { key: "featured", label: "Featured (most popular)", type: "boolean" },
    ],
  },

  faqItems: {
    label: "FAQs",
    singular: "FAQ",
    idKey: "q",
    titleKey: "q",
    fields: [
      { key: "q", label: "Question", type: "text", required: true },
      { key: "a", label: "Answer", type: "textarea", required: true },
    ],
  },

  insights: {
    label: "Insights",
    singular: "Article",
    idKey: "slug",
    titleKey: "title",
    fields: [
      commonFields.slug,
      commonFields.title,
      { key: "excerpt", label: "Excerpt", type: "textarea" },
      { key: "category", label: "Category", type: "text" },
      { key: "readTime", label: "Read time (e.g. 6 min read)", type: "text" },
      { key: "date", label: "Date (YYYY-MM-DD)", type: "text" },
      { key: "author", label: "Author", type: "text" },
      {
        key: "content",
        label: "Content blocks",
        type: "objects-list",
        subFields: [
          { key: "type", label: "Type (p/h2)", type: "select", options: ["p", "h2"] },
          { key: "text", label: "Text", type: "textarea" },
        ],
      },
    ],
  },

  clientBrands: {
    label: "Client Brands",
    singular: "Brand",
    idKey: "name",
    titleKey: "name",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "industry", label: "Industry", type: "text" },
    ],
  },
};

export const collectionOrder = [
  "portfolioItems",
  "serviceCategories",
  "teamRoles",
  "testimonials",
  "caseStudies",
  "pricingPlans",
  "insights",
  "faqItems",
  "clientBrands",
];
